### ISSUE TITLE
Dosen't work on Android 5.0

### ISSUE THREAD

**Issue by apollon0815** [Red-Folder/bgs-core#18]
Hello,

thank you for this wonderful plugin. 

It works very well on Android 4.4 and lower. 
But when I test it with Eclipse and Android 5 SDK on an Android 5.0 emulator, background service not starting.

I hope you can fix it.

Thank you very much.

Log:

10-24 14:46:58.119: D/BackgroundServicePluginLogic(1206): Start of Execute
10-24 14:46:58.120: D/BackgroundServicePluginLogic(1206): Withing try block
10-24 14:46:58.122: D/BackgroundServicePluginLogic(1206): Finding servicename com.domain.demoapp.MyService
10-24 14:46:58.122: D/BackgroundServicePluginLogic(1206): Services contain 0 records
10-24 14:46:58.123: D/BackgroundServicePluginLogic(1206): Creating new Service Details
10-24 14:46:58.132: W/PluginManager(1206): THREAD WARNING: exec() call to BackgroundServicePlugin.getStatus blocked the main thread for 231ms. Plugin should use CordovaInterface.getThreadPool().
10-24 14:47:00.176: W/PluginManager(1206): THREAD WARNING: exec() call to File.getFile blocked the main thread for 264ms. Plugin should use CordovaInterface.getThreadPool().
10-24 14:47:03.076: D/BackgroundServicePluginLogic(1206): Action = getStatus
10-24 14:47:03.211: D/BackgroundServicePlugin(1206): logicResult = com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ExecuteResult@389df6c2
10-24 14:47:03.251: D/BackgroundServicePlugin(1206): Start of transformResult
10-24 14:47:03.266: D/BackgroundServicePlugin(1206): Status is OK
10-24 14:47:03.267: D/BackgroundServicePlugin(1206): We have data
10-24 14:47:03.269: D/BackgroundServicePlugin(1206): End of transformResult
10-24 14:47:03.270: D/BackgroundServicePlugin(1206): pluginResult = org.apache.cordova.PluginResult@187d5cd3
10-24 14:47:03.272: D/BackgroundServicePlugin(1206): pluginResult.getMessage() = {"Success":true,"ErrorCode":0,"ErrorMessage":"","ServiceRunning":false,"RegisteredForBootStart":false,"RegisteredForUpdates":false}
10-24 14:47:03.272: D/BackgroundServicePlugin(1206): Dont keep Callback
10-24 14:47:04.200: D/BackgroundServicePluginLogic(1206): Start of Execute
10-24 14:47:04.201: D/BackgroundServicePluginLogic(1206): Withing try block
10-24 14:47:04.202: D/BackgroundServicePluginLogic(1206): Finding servicename com.domain.demoapp.MyService
10-24 14:47:04.366: D/BackgroundServicePluginLogic(1206): Services contain 1 records
10-24 14:47:04.367: D/BackgroundServicePluginLogic(1206): Found existing Service Details
10-24 14:47:04.368: D/BackgroundServicePluginLogic(1206): Action = startService
10-24 14:47:04.368: D/ServiceDetails(1206): Starting startService
10-24 14:47:04.368: D/ServiceDetails(1206): Attempting to bind to Service
10-24 14:47:04.369: D/ServiceDetails(1206): Starting bindToService
10-24 14:47:04.427: D/ServiceDetails(1206): Attempting to start service
10-24 14:47:04.632: D/ServiceDetails(1206): bindToService failed
10-24 14:47:04.632: D/ServiceDetails(1206): java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.domain.demoapp.MyService }
10-24 14:47:04.632: D/ServiceDetails(1206): 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1703)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at android.app.ContextImpl.startService(ContextImpl.java:1687)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at android.content.ContextWrapper.startService(ContextWrapper.java:515)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ServiceDetails.bindToService(BackgroundServicePluginLogic.java:604)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ServiceDetails.startService(BackgroundServicePluginLogic.java:335)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic.execute(BackgroundServicePluginLogic.java:188)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePlugin$1.run(BackgroundServicePlugin.java:68)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-24 14:47:04.632: D/ServiceDetails(1206): 	at java.lang.Thread.run(Thread.java:818)
10-24 14:47:04.653: D/ServiceDetails(1206): Finished bindToService
10-24 14:47:04.654: D/ServiceDetails(1206): Bind Failed
10-24 14:47:04.655: D/ServiceDetails(1206): Finished startService
10-24 14:47:04.656: D/BackgroundServicePlugin(1206): logicResult = com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ExecuteResult@3ddb0010
10-24 14:47:04.656: D/BackgroundServicePlugin(1206): Start of transformResult
10-24 14:47:04.656: D/BackgroundServicePlugin(1206): Status is ERROR
10-24 14:47:04.657: D/BackgroundServicePlugin(1206): We have data
10-24 14:47:04.657: D/BackgroundServicePlugin(1206): End of transformResult
10-24 14:47:04.657: D/BackgroundServicePlugin(1206): pluginResult = org.apache.cordova.PluginResult@2ca41709
10-24 14:47:04.658: D/BackgroundServicePlugin(1206): pluginResult.getMessage() = {"Success":false,"ErrorCode":-4,"ErrorMessage":"Plugin unable to bind to background service","ServiceRunning":false,"RegisteredForBootStart":false,"RegisteredForUpdates":false}
10-24 14:47:04.658: D/BackgroundServicePlugin(1206): Dont keep Callback

**Comment by lylepratt** [comment]
I'm to the point where I am forced to update to sdk version 21. Now that I have, i'm back to this problem. Anyone have any advice?

**Comment by hectorg83** [comment]
Hi, I am working with the last version of this plugin and the last version of apache cordova. 

I have a problem with this plugin in Android 5, Nexus 5.

I tested the plugin with the example https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample and It doesn´t work.

When I press the button Service, I receive the next error: Plugin unable to bind background service.

The same example works in android 4.4 (Nexus 5), adroid ice-cream and android jelly bean.

**Comment by hectorg83** [comment]
Thank you so much niarferuto. I solved the problem with your corrections.

**Comment by Red-Folder** [comment]
Finally I can replicate this

Needed build against V21 (app & cordovalib) and run against V21 emulator.

Now to fix it

**Comment by Red-Folder** [comment]
Fixed in commit 167a4f7789f1162ac358278f8da7c82761c7feef

Test on emulator versions:

* Android 2.3.3/ Version 10
* Android 4.4.2/ Version 19
* Android 5.0.1/ Version 21

**Comment by hectorg83** [comment]
Thank you so much Red-Folder! ;)

**Comment by alexandreetf** [comment]
Hi!
I'm trying to run in Android 5, but the service doesn't start on boot. When i open the app run perfectly.
But on boot, the console log show: 
04-04 01:30:06.665: I/ActivityManager(937): Waited long enough for: ServiceRecord{18f53d58 u0 com.ionicframework.back337261/com.red_folder.phonegap.plugin.backgroundservice.sample.MyService}

Someone could help me?

**Comment by MarkVlamPersie** [comment]
Hello Red-Folder,

I'm currently trying to use your tutorial to create a background service for my android application. I have used the exact same names as you have, because i wanted to get it to work in the first place. I get the exact same errormessage as mentioned above. 

Plugin unable to bind to background service.

I've tried all the fixes mentioned above as well, but it does not fix the problem. I have been stuck with this problem for a few days now and i now hope you can help me any further, any chance you see what the problem is?

The code i currently have on line 601 in the file BackgroundServicePluginLogic.java is, as mentioned above by niarferuto:
`				// Fix to https://github.com/Red-Folder/bgs-core/issues/18
				// Gets the class from string
				Class<?> serviceClass = ReflectionHelper.LoadClass(this.mServiceName);
        this.mService = new Intent(this.mContext, MyService.class);`

i've also tried the solutions you mentioned. But they don't fix my problem.

**Comment by fovaka1** [comment]
Hello to everyone,

i am facing the same problem with MarkVlamPersie.

Is there a workaround?

The version of BackgroundServicePluginLogic.java that i have is already corrected according to above fixes, but still my app says "Plugin unable to bind to background service"

Thank you very much.

**Comment by MarkVlamPersie** [comment]
Fovaka1,

I have opened a thread on Stackoverflow for this. Since JugnuPathak who opened a new issue seems to face the same problem. Would be nice if you could upvote [this](http://stackoverflow.com/questions/37204259/plugin-unable-to-bind-to-background-service-red-folder-phonegap-plugin).

Also if you do run into a solution can you post it here?

**Comment by fovaka1** [comment]
Thank you for pointing out.

In case of a solution i will post here also, yes.

**Comment by fovaka1** [comment]
Found it!!!!:)

Firstly check that you have 

# package com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;

inside MyService.java on top. 

I did not notice that was missing.

After you do that go to file com.red_folder.phonegap.plugin.backgroundservice.BackgroundService.BackgroundServicePluginLogic.java

line 163 and change 

String serviceName =  data.getString(0);

to 

String serviceName = "com.red_folder.phonegap.plugin.backgroundservice.BackgroundService.MyService";




Otherwise i followed below steps(i did this one first and is working but i think the above could be also a solution, so as not to change files, positions etc..).

1. move MyService.java from com.red_folder.phonegap.plugin.backgroundservice.BackgroundService to com.my.app

2.MyService.java is the following

/*********************************/
package com.my.app;

import android.util.Log;

import com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;

import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;

public class MyService extends BackgroundService {

    @Override
    protected JSONObject doWork() {
        JSONObject result = new JSONObject();

        try {
            // Following three lines simply produce a text string with Hello World and the date & time (UK format)
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String now = df.format(new Date(System.currentTimeMillis()));
            String msg = "Hello World - its currently " + now;

            // We output the message to the logcat
            Log.d("MyService", msg);

            // We also provide the same message in our JSON Result
            result.put("Message", msg);
        } catch (JSONException e) {
            // In production code, you would have some exception handling here
        }

        return result;
    }

    @Override
    protected JSONObject getConfig() {
        return null;
    }

    @Override
    protected void setConfig(JSONObject config) {

    }

    @Override
    protected JSONObject initialiseLatestResult() {
        return null;
    }

}

/*********************************/


3. Change also in AndroidManifest.xml

        <service android:name="com.my.app.MyService">
            <intent-filter>
                <action android:name="com.my.app.MyService" />
            </intent-filter>
        </service>



4. Go to file com.red_folder.phonegap.plugin.backgroundservice.BackgroundService.BackgroundServicePluginLogic.java

line 163 and change 

String serviceName =  data.getString(0);

to 

String serviceName = "com.my.app.MyService";

i hope to help you!!!

**Comment by MarkVlamPersie** [comment]
Hmmm,

I've tried your solution, and it doesn't work for me. but i think i haven't implemented it in the right way.
My directories look as follows:
com.red_folder.phonegap.plugin.backgroundservice
```
--------------->aidl
--------------------->(some files here)
--------------->sample
--------------------->MyService.java
--------------->src
--------------------->android
------------------------------>BackgroundService.java
------------------------------>BackgroundServicePluginLogi.java 
------------------------------>(the other included files)
--------------->www
--------------------->backgroundService.js

```
Now my MyService.java class looks like:
```
package com.red_folder.phonegap.plugin.backgroundservice.sample;

import com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;
import org.json.JSONException;
import org.json.JSONObject;

import android.util.Log;
import java.text.SimpleDateFormat;
import java.util.Date;

public class MyService extends BackgroundService {
//code from tutorial here
}
```
You said to set the package to:
`package com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;`

I've put that as the package as well as on top of the package. But neither fix the problem.

And my android manifest looks like:
```
        <service android:name="com.red_folder.phonegap.plugin.backgroundservice.sample.MyService">
            <intent-filter>
                <action android:name="com.red_folder.phonegap.plugin.backgroundservice.sample.MyService" />
            </intent-filter>
        </service>
```

Then as you said, i changed line 163 in BackgroundServicePluginLogic.java to:
`		String serviceName = "com.red_folder.phonegap.plugin.backgroundservice.sample.MyService";`

Is there anything i've done wrong or missed from you solution?

**Comment by fovaka1** [comment]
Try this,

get your MyService.java file and put it inside your main directory

com.my.app

change package of course accordingly.

change manifest accordingly

leave line 163 in BackgroundServicePluginLogic.java as use before and just put this inside app.js

var serviceName = 'com.my.app.MyService';
    var factory = cordova.require('com.red_folder.phonegap.plugin.backgroundservice.BackgroundService')
    myService = factory.create(serviceName);
    go();
......
The rest of the functions are the same here.

**Comment by MarkVlamPersie** [comment]
I've tried it, but it doesn't fix my issue. What android version are you using?

**Comment by fovaka1** [comment]
Tested with Android Devices 4.3 and 5.1 and both work just fine.

Cordova version 6.1.1

Take android folder (IONIC) and open it with Android Studio.

Try the above changes again.

**Comment by MarkVlamPersie** [comment]
@fovaka1 it wont work for me. I'll try starting a new project and see if it works there. Thanks for your clear instructions though!

**Comment by Red-Folder** [comment]
@MarkVlamPersie @fovaka1 Thanks for contributing you comments to the issue.

**Comment by MarkVlamPersie** [comment]
@Red-Folder unfortunately it still won't work for me. Do you have any suggestions on changes that could fix it?

I have followed your instructions from the tutorial and i've tried it multiple times but it wont work. I've tried multiple fixes my self. Few things i have noticed so far are:
- i can't find MyService.java in the build version after putting:
`$ ionic build android` in the command line. Is this a problem? If so, where should it be and how can i fix this? 

- MyService,Java is not defined in plugin.xml as a source file. I've tried adding it myself like this:   

`<source-file src="sample/MyService.java" target-dir="src/com/red_folder/phonegap/plugin/backgroundservice" />`
but it does not help.

- backgroundService.js from the plugin is different after building it. Namely on top of it in the plugin-version i starts with:
```
//a large comment
function BackgroundServiceFactory() { }

BackgroundServiceFactory.prototype.create = function (serviceName) {
//Some code here
}
```
Then after building, i looked up the same file in the platforms/android directory and found the file like this:
```
cordova.define("com.red_folder.phonegap.plugin.backgroundservice.BackgroundService", function(require, exports, module) {
//and then the above mentioned code inbetween the brackets.
}
```

**Comment by MarkVlamPersie** [comment]
I've now finally got it to work. The problem was that MyService.java was excluded from the build when i used the command: `ionic build android`. I have fixed this problem litteraly by just putting `MyService.java` in the build directory with the other java-files. 

Thanks for all the help.

**Comment by Red-Folder** [comment]
@MarkVlamPersie Great news that its working.  Could I ask a favour please

Could you review the documention -> https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample

If there are changes you feel that would be appropriate given you experience it would be much appreciated.  Thanks

**Comment by MarkVlamPersie** [comment]
@Red-Folder Sure! I will take a look at it this evening if i can find the time. If not i'll do it tomorrow.

**Comment by MarkVlamPersie** [comment]
@Red-Folder Firstly, sorry for very delayed response.

I haven't worked with that documentation since i used the tutorial to implement the backgroundservice in my application. I think [this](https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample) documentation is very clear. The only thing that i could possibly think of to edit to the tutorial documentation is to provide the package for you example in code lines. In step 2 something similar to:
`package com.red_folder.phonegap.plugin.backgroundservice.sample;`

Also the documentation is still up-to-date and the plugin should work if you implement it correctly(, unlike me).

That's basicly all i can say, since the documentation is very clear and most of the code quite self explanatory.

**Comment by nitzpb** [comment]
hi, Mark can u help me please.
i'm stuck at same point where u had before.

I've tried your solution, and it doesn't work for me. but i think i haven't implemented it in the right way.
My directories look as follows:
com.red_folder.phonegap.plugin.backgroundservice

--------------->aidl
--------------------->(some files here)
--------------->sample
--------------------->MyService.java
--------------->src
--------------------->android
------------------------------>BackgroundService.java
------------------------------>BackgroundServicePluginLogi.java 
------------------------------>(the other included files)
--------------->www
--------------------->backgroundService.js

Now my MyService.java class looks like:

package com.red_folder.phonegap.plugin.backgroundservice.sample;

import com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;
import org.json.JSONException;
import org.json.JSONObject;

import android.util.Log;
import java.text.SimpleDateFormat;
import java.util.Date;

public class MyService extends BackgroundService {
//code from tutorial here
}
You said to set the package to:
package com.red_folder.phonegap.plugin.backgroundservice.BackgroundService;

I've put that as the package as well as on top of the package. But neither fix the problem.

And my android manifest looks like:

        <service android:name="com.red_folder.phonegap.plugin.backgroundservice.sample.MyService">
            <intent-filter>
                <action android:name="com.red_folder.phonegap.plugin.backgroundservice.sample.MyService" />
            </intent-filter>
        </service>
Then as you said, i changed line 163 in BackgroundServicePluginLogic.java to:
String serviceName = "com.red_folder.phonegap.plugin.backgroundservice.sample.MyService";

Is there anything i've done wrong or missed from you solution?

what i go next from this position can u guide me.??
im getting error report on console is-

Error: Plugin unable to bind to background service

and 
 java Script Alert come from code is-

ErrorCode: -4, Success: false, RegisteredForUpdates:false,RegisteredForBootStart:false,ErrorMessage: Plugin unable to to bind to background service,ServiceRunning: false

i spend couple of days on this to solve the problem.

**Comment by nitzpb** [comment]
Hey MarkVlamPersie,
can u explain how u do this.?

I've now finally got it to work. The problem was that MyService.java was excluded from the build when i used the command: ionic build android. I have fixed this problem litteraly by just putting MyService.java in the build directory with the other java-files.

**Comment by nitzpb** [comment]
# @MarkVlamPersie  im trying 
all possible solutions but its still not working.

**Comment by MarkVlamPersie** [comment]
Hey @nitzpb ,

I have not worked with this plugin for about a year now, so i find it a bit hard to remember everything i did since i do not have the source code itself anymore. You seem to have taken the right steps.

My problem was that i when i used the build command a few Java files were excluded. What you need to do is take a look in the build folder after you have used the build command and see if all the Java files that are in your project also are in the build folder. If some are missing you need to copy those java files from your project to the build folder. E.g. for me the MyService.java was excluded fromt the build and i was not in the build folder after using the build command, so i copied the MyService.java from the source folder to the build folder. That was what solved the problem for me. 

I hope this helps you with your problem.

**Comment by nitzpb** [comment]
finally, its solved.
im missing MyService.js file.

**Comment by nitzpb** [comment]
Thank u for Ur reply.
I manage that issue.
Actually, I'm missed the MyService.js file to add in plugin.
When I add that file and re-install the bg-core plugin its works.
Thank u for uploading this helpful plugin on github.
And
Sorry for my bad English.

Regards,
Niteen Bhende.

**Comment by deepakjsr7979** [comment]
This service Not working in Android 10. any help ?
